// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using restaurant_medii.Data;

#nullable disable

namespace restaurant_medii.Migrations
{
    [DbContext(typeof(restaurant_mediiContext))]
    [Migration("20260106165122_Alergeni")]
    partial class Alergeni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("restaurant_medii.Models.Alergen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NumeAlergen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Alergen");
                });

            modelBuilder.Entity("restaurant_medii.Models.AlergenProdus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AlergenID")
                        .HasColumnType("int");

                    b.Property<int>("ProdusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AlergenID");

                    b.HasIndex("ProdusID");

                    b.ToTable("AlergenProdus");
                });

            modelBuilder.Entity("restaurant_medii.Models.Categorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AlergenID")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AlergenID");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("restaurant_medii.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategorieID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("restaurant_medii.Models.AlergenProdus", b =>
                {
                    b.HasOne("restaurant_medii.Models.Alergen", "Alergen")
                        .WithMany()
                        .HasForeignKey("AlergenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("restaurant_medii.Models.Produs", "Produs")
                        .WithMany("AlergeniProduse")
                        .HasForeignKey("ProdusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alergen");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("restaurant_medii.Models.Categorie", b =>
                {
                    b.HasOne("restaurant_medii.Models.Alergen", null)
                        .WithMany("Categorii")
                        .HasForeignKey("AlergenID");
                });

            modelBuilder.Entity("restaurant_medii.Models.Produs", b =>
                {
                    b.HasOne("restaurant_medii.Models.Categorie", "Categorie")
                        .WithMany("Produse")
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("restaurant_medii.Models.Alergen", b =>
                {
                    b.Navigation("Categorii");
                });

            modelBuilder.Entity("restaurant_medii.Models.Categorie", b =>
                {
                    b.Navigation("Produse");
                });

            modelBuilder.Entity("restaurant_medii.Models.Produs", b =>
                {
                    b.Navigation("AlergeniProduse");
                });
#pragma warning restore 612, 618
        }
    }
}
